<Red@Image>:
  source: 'red.png'
  fit_mode: 'scale-down'
  size_hint: [1, 1/6]
  color: [1,1,1,app.opacity]

<Yellow@Image>
  source: 'yellow.png'
  fit_mode: 'scale-down'
  size_hint: [1, 1/6]
  color: [1,1,1,app.opacity]

<EmptyStackLayout@StackLayout>:
  orientation: 'bt-lr'

<ColumnButton@Button>:
  background_color: (144/88,238/88,144/88,1)
  background_disabled_normal: 'light_red.png'
  markup: True